// AUTO-GENERATED — do not edit manually. Run: node scripts/generate-glyphs.mjs
import type { ViewStyle } from 'react-native'
type GlyphFC = React.ComponentType<{ size?: number; color?: string; style?: ViewStyle }>
export function lookupNativeGlyph(name: string): GlyphFC | null {
  switch (name) {
    case 'Acorn': return require('./Acorn').default
    case 'Alarm': return require('./Alarm').default
    case 'Anchor': return require('./Anchor').default
    case 'Ankh': return require('./Ankh').default
    case 'Anvil': return require('./Anvil').default
    case 'Apple': return require('./Apple').default
    case 'Archive': return require('./Archive').default
    case 'ArrowDownRight': return require('./ArrowDownRight').default
    case 'ArrowDown': return require('./ArrowDown').default
    case 'ArrowLeft': return require('./ArrowLeft').default
    case 'ArrowRight': return require('./ArrowRight').default
    case 'ArrowUpRight': return require('./ArrowUpRight').default
    case 'ArrowUp': return require('./ArrowUp').default
    case 'Asterism': return require('./Asterism').default
    case 'AtSign': return require('./AtSign').default
    case 'Atm': return require('./Atm').default
    case 'Award': return require('./Award').default
    case 'Axe': return require('./Axe').default
    case 'BabyBottle': return require('./BabyBottle').default
    case 'Backpack': return require('./Backpack').default
    case 'Bag': return require('./Bag').default
    case 'Balloon': return require('./Balloon').default
    case 'Ban': return require('./Ban').default
    case 'Bandage': return require('./Bandage').default
    case 'Bank': return require('./Bank').default
    case 'Barcode': return require('./Barcode').default
    case 'Basket': return require('./Basket').default
    case 'Battery': return require('./Battery').default
    case 'Bed': return require('./Bed').default
    case 'Beer': return require('./Beer').default
    case 'BellOff': return require('./BellOff').default
    case 'Bell': return require('./Bell').default
    case 'Bike': return require('./Bike').default
    case 'Bird': return require('./Bird').default
    case 'Bitcoin': return require('./Bitcoin').default
    case 'Blocks': return require('./Blocks').default
    case 'Bolt': return require('./Bolt').default
    case 'Bone': return require('./Bone').default
    case 'Book': return require('./Book').default
    case 'Bookmark': return require('./Bookmark').default
    case 'Bottle': return require('./Bottle').default
    case 'Box': return require('./Box').default
    case 'Brain': return require('./Brain').default
    case 'Bread': return require('./Bread').default
    case 'Briefcase': return require('./Briefcase').default
    case 'Broom': return require('./Broom').default
    case 'Brush': return require('./Brush').default
    case 'Bug': return require('./Bug').default
    case 'Building': return require('./Building').default
    case 'Burger': return require('./Burger').default
    case 'Bus': return require('./Bus').default
    case 'Cactus': return require('./Cactus').default
    case 'Cake': return require('./Cake').default
    case 'Calculator': return require('./Calculator').default
    case 'CalendarCheck': return require('./CalendarCheck').default
    case 'Calendar': return require('./Calendar').default
    case 'Camera': return require('./Camera').default
    case 'Campfire': return require('./Campfire').default
    case 'Candle': return require('./Candle').default
    case 'Candy': return require('./Candy').default
    case 'Car': return require('./Car').default
    case 'CaretDown': return require('./CaretDown').default
    case 'CaretLeft': return require('./CaretLeft').default
    case 'CaretRight': return require('./CaretRight').default
    case 'CaretUp': return require('./CaretUp').default
    case 'Cart': return require('./Cart').default
    case 'Cat': return require('./Cat').default
    case 'ChartBar': return require('./ChartBar').default
    case 'ChartLine': return require('./ChartLine').default
    case 'ChartPie': return require('./ChartPie').default
    case 'ChatDots': return require('./ChatDots').default
    case 'Chat': return require('./Chat').default
    case 'CheckCircle': return require('./CheckCircle').default
    case 'Chess': return require('./Chess').default
    case 'ChevronDown': return require('./ChevronDown').default
    case 'ChevronLeft': return require('./ChevronLeft').default
    case 'ChevronRight': return require('./ChevronRight').default
    case 'ChevronUp': return require('./ChevronUp').default
    case 'ChevronsLeft': return require('./ChevronsLeft').default
    case 'ChevronsRight': return require('./ChevronsRight').default
    case 'Circle': return require('./Circle').default
    case 'Clapperboard': return require('./Clapperboard').default
    case 'Clipboard': return require('./Clipboard').default
    case 'Clock': return require('./Clock').default
    case 'Close': return require('./Close').default
    case 'CloudRain': return require('./CloudRain').default
    case 'CloudSun': return require('./CloudSun').default
    case 'Cloud': return require('./Cloud').default
    case 'Cocktail': return require('./Cocktail').default
    case 'Coffee': return require('./Coffee').default
    case 'Coin': return require('./Coin').default
    case 'Coins': return require('./Coins').default
    case 'Collapse': return require('./Collapse').default
    case 'Columns': return require('./Columns').default
    case 'Comet': return require('./Comet').default
    case 'Comments': return require('./Comments').default
    case 'Compass': return require('./Compass').default
    case 'Cookie': return require('./Cookie').default
    case 'Copy': return require('./Copy').default
    case 'Couch': return require('./Couch').default
    case 'Cpu': return require('./Cpu').default
    case 'CreditCard': return require('./CreditCard').default
    case 'Croissant': return require('./Croissant').default
    case 'Cross': return require('./Cross').default
    case 'Crosshair': return require('./Crosshair').default
    case 'Crown': return require('./Crown').default
    case 'Crystal': return require('./Crystal').default
    case 'Cup': return require('./Cup').default
    case 'Database': return require('./Database').default
    case 'Dice': return require('./Dice').default
    case 'Dog': return require('./Dog').default
    case 'Dollar': return require('./Dollar').default
    case 'Donut': return require('./Donut').default
    case 'Door': return require('./Door').default
    case 'Download': return require('./Download').default
    case 'DraftingCompass': return require('./DraftingCompass').default
    case 'Drag': return require('./Drag').default
    case 'Dress': return require('./Dress').default
    case 'Droplet': return require('./Droplet').default
    case 'Dumbbell': return require('./Dumbbell').default
    case 'Edit': return require('./Edit').default
    case 'Egg': return require('./Egg').default
    case 'ElementAir': return require('./ElementAir').default
    case 'ElementEarth': return require('./ElementEarth').default
    case 'ElementFire': return require('./ElementFire').default
    case 'ElementWater': return require('./ElementWater').default
    case 'Eraser': return require('./Eraser').default
    case 'Euro': return require('./Euro').default
    case 'Exchange': return require('./Exchange').default
    case 'Expand': return require('./Expand').default
    case 'ExternalLink': return require('./ExternalLink').default
    case 'EyeOff': return require('./EyeOff').default
    case 'Eye': return require('./Eye').default
    case 'Factory': return require('./Factory').default
    case 'Feather': return require('./Feather').default
    case 'Fern': return require('./Fern').default
    case 'FilePlus': return require('./FilePlus').default
    case 'File': return require('./File').default
    case 'Film': return require('./Film').default
    case 'Filter': return require('./Filter').default
    case 'Fingerprint': return require('./Fingerprint').default
    case 'FireExtinguisher': return require('./FireExtinguisher').default
    case 'Fire': return require('./Fire').default
    case 'FirstAid': return require('./FirstAid').default
    case 'FishHook': return require('./FishHook').default
    case 'Fish': return require('./Fish').default
    case 'Flag': return require('./Flag').default
    case 'Flask': return require('./Flask').default
    case 'Flourish': return require('./Flourish').default
    case 'Flower': return require('./Flower').default
    case 'FolderOpen': return require('./FolderOpen').default
    case 'Folder': return require('./Folder').default
    case 'Fuel': return require('./Fuel').default
    case 'Gamepad': return require('./Gamepad').default
    case 'Gavel': return require('./Gavel').default
    case 'Gear': return require('./Gear').default
    case 'Gem': return require('./Gem').default
    case 'Gift': return require('./Gift').default
    case 'Glasses': return require('./Glasses').default
    case 'Globe': return require('./Globe').default
    case 'Grid': return require('./Grid').default
    case 'Guitar': return require('./Guitar').default
    case 'Hammer': return require('./Hammer').default
    case 'HandCoin': return require('./HandCoin').default
    case 'Hand': return require('./Hand').default
    case 'Hanger': return require('./Hanger').default
    case 'HardDrive': return require('./HardDrive').default
    case 'Hat': return require('./Hat').default
    case 'Headphones': return require('./Headphones').default
    case 'HeartFilled': return require('./HeartFilled').default
    case 'HeartPulse': return require('./HeartPulse').default
    case 'Heart': return require('./Heart').default
    case 'Help': return require('./Help').default
    case 'Hex': return require('./Hex').default
    case 'Hexagram': return require('./Hexagram').default
    case 'History': return require('./History').default
    case 'Home': return require('./Home').default
    case 'Hospital': return require('./Hospital').default
    case 'Hourglass': return require('./Hourglass').default
    case 'IceCream': return require('./IceCream').default
    case 'Image': return require('./Image').default
    case 'Inbox': return require('./Inbox').default
    case 'Info': return require('./Info').default
    case 'KeyRound': return require('./KeyRound').default
    case 'Key': return require('./Key').default
    case 'Keyboard': return require('./Keyboard').default
    case 'Lamp': return require('./Lamp').default
    case 'Laptop': return require('./Laptop').default
    case 'Layers': return require('./Layers').default
    case 'Leaf': return require('./Leaf').default
    case 'Lightbulb': return require('./Lightbulb').default
    case 'Link': return require('./Link').default
    case 'Lipstick': return require('./Lipstick').default
    case 'List': return require('./List').default
    case 'Lock': return require('./Lock').default
    case 'Lotus': return require('./Lotus').default
    case 'Luggage': return require('./Luggage').default
    case 'Magnet': return require('./Magnet').default
    case 'MailOpen': return require('./MailOpen').default
    case 'Mail': return require('./Mail').default
    case 'Map': return require('./Map').default
    case 'Mark': return require('./Mark').default
    case 'Mars': return require('./Mars').default
    case 'Mask': return require('./Mask').default
    case 'Maximize': return require('./Maximize').default
    case 'Megaphone': return require('./Megaphone').default
    case 'Menu': return require('./Menu').default
    case 'Mercury': return require('./Mercury').default
    case 'MicOff': return require('./MicOff').default
    case 'Mic': return require('./Mic').default
    case 'Milk': return require('./Milk').default
    case 'MinusCircle': return require('./MinusCircle').default
    case 'Minus': return require('./Minus').default
    case 'MoneyBill': return require('./MoneyBill').default
    case 'Monitor': return require('./Monitor').default
    case 'Moon': return require('./Moon').default
    case 'MoreVertical': return require('./MoreVertical').default
    case 'More': return require('./More').default
    case 'MortarPestle': return require('./MortarPestle').default
    case 'Mountain': return require('./Mountain').default
    case 'Mushroom': return require('./Mushroom').default
    case 'MusicNote': return require('./MusicNote').default
    case 'Navigation': return require('./Navigation').default
    case 'Needle': return require('./Needle').default
    case 'Noodles': return require('./Noodles').default
    case 'Note': return require('./Note').default
    case 'NutBolt': return require('./NutBolt').default
    case 'Palette': return require('./Palette').default
    case 'PalmTree': return require('./PalmTree').default
    case 'Paperclip': return require('./Paperclip').default
    case 'Parking': return require('./Parking').default
    case 'Passport': return require('./Passport').default
    case 'Pause': return require('./Pause').default
    case 'Paw': return require('./Paw').default
    case 'Pencil': return require('./Pencil').default
    case 'People': return require('./People').default
    case 'Percent': return require('./Percent').default
    case 'Perfume': return require('./Perfume').default
    case 'PersonAdd': return require('./PersonAdd').default
    case 'Person': return require('./Person').default
    case 'Phone': return require('./Phone').default
    case 'Piano': return require('./Piano').default
    case 'Pickaxe': return require('./Pickaxe').default
    case 'PiggyBank': return require('./PiggyBank').default
    case 'Pill': return require('./Pill').default
    case 'Pin': return require('./Pin').default
    case 'Pizza': return require('./Pizza').default
    case 'Plane': return require('./Plane').default
    case 'Planet': return require('./Planet').default
    case 'PlayCircle': return require('./PlayCircle').default
    case 'Play': return require('./Play').default
    case 'Plug': return require('./Plug').default
    case 'PlusCircle': return require('./PlusCircle').default
    case 'Plus': return require('./Plus').default
    case 'Popcorn': return require('./Popcorn').default
    case 'Potion': return require('./Potion').default
    case 'Pound': return require('./Pound').default
    case 'Printer': return require('./Printer').default
    case 'Puzzle': return require('./Puzzle').default
    case 'Qr': return require('./Qr').default
    case 'Quintessence': return require('./Quintessence').default
    case 'Rainbow': return require('./Rainbow').default
    case 'Receipt': return require('./Receipt').default
    case 'Redo': return require('./Redo').default
    case 'Refresh': return require('./Refresh').default
    case 'Restaurant': return require('./Restaurant').default
    case 'Ring': return require('./Ring').default
    case 'Road': return require('./Road').default
    case 'Rocket': return require('./Rocket').default
    case 'Router': return require('./Router').default
    case 'Rss': return require('./Rss').default
    case 'Ruler': return require('./Ruler').default
    case 'Running': return require('./Running').default
    case 'Salad': return require('./Salad').default
    case 'Salt': return require('./Salt').default
    case 'Save': return require('./Save').default
    case 'Saw': return require('./Saw').default
    case 'Scale': return require('./Scale').default
    case 'Scales': return require('./Scales').default
    case 'School': return require('./School').default
    case 'Scissors': return require('./Scissors').default
    case 'Scooter': return require('./Scooter').default
    case 'Screwdriver': return require('./Screwdriver').default
    case 'Scroll': return require('./Scroll').default
    case 'Search': return require('./Search').default
    case 'Send': return require('./Send').default
    case 'Server': return require('./Server').default
    case 'Settings': return require('./Settings').default
    case 'Share': return require('./Share').default
    case 'ShieldCheck': return require('./ShieldCheck').default
    case 'ShieldKey': return require('./ShieldKey').default
    case 'Shield': return require('./Shield').default
    case 'Ship': return require('./Ship').default
    case 'Shirt': return require('./Shirt').default
    case 'Shoe': return require('./Shoe').default
    case 'Shovel': return require('./Shovel').default
    case 'Sidebar': return require('./Sidebar').default
    case 'SigilBlade': return require('./SigilBlade').default
    case 'SigilCardinal': return require('./SigilCardinal').default
    case 'SigilEye': return require('./SigilEye').default
    case 'SigilFeather': return require('./SigilFeather').default
    case 'SigilFlame': return require('./SigilFlame').default
    case 'SigilFlask': return require('./SigilFlask').default
    case 'SigilHeptagram': return require('./SigilHeptagram').default
    case 'SigilHexnested': return require('./SigilHexnested').default
    case 'SigilKey': return require('./SigilKey').default
    case 'SigilLeaf': return require('./SigilLeaf').default
    case 'SigilMoon': return require('./SigilMoon').default
    case 'SigilOctagram': return require('./SigilOctagram').default
    case 'SigilPentagram': return require('./SigilPentagram').default
    case 'SigilSolomon': return require('./SigilSolomon').default
    case 'SigilSpiralsquare': return require('./SigilSpiralsquare').default
    case 'SigilTriquetra': return require('./SigilTriquetra').default
    case 'SigilVesica': return require('./SigilVesica').default
    case 'SigilWheel': return require('./SigilWheel').default
    case 'Sigil': return require('./Sigil').default
    case 'SkipBack': return require('./SkipBack').default
    case 'SkipForward': return require('./SkipForward').default
    case 'Skull': return require('./Skull').default
    case 'Sliders': return require('./Sliders').default
    case 'Smartphone': return require('./Smartphone').default
    case 'Snowflake': return require('./Snowflake').default
    case 'Snowman': return require('./Snowman').default
    case 'Soda': return require('./Soda').default
    case 'Sort': return require('./Sort').default
    case 'Spinner': return require('./Spinner').default
    case 'Sprig': return require('./Sprig').default
    case 'Sprout': return require('./Sprout').default
    case 'Square': return require('./Square').default
    case 'StarFilled': return require('./StarFilled').default
    case 'Star': return require('./Star').default
    case 'Stethoscope': return require('./Stethoscope').default
    case 'Stop': return require('./Stop').default
    case 'Store': return require('./Store').default
    case 'Stroller': return require('./Stroller').default
    case 'Sulfur': return require('./Sulfur').default
    case 'Sun': return require('./Sun').default
    case 'Sunglasses': return require('./Sunglasses').default
    case 'Sunrise': return require('./Sunrise').default
    case 'Sushi': return require('./Sushi').default
    case 'Syringe': return require('./Syringe').default
    case 'Taco': return require('./Taco').default
    case 'Tag': return require('./Tag').default
    case 'Target': return require('./Target').default
    case 'Taxi': return require('./Taxi').default
    case 'Teddy': return require('./Teddy').default
    case 'Tent': return require('./Tent').default
    case 'TheaterMasks': return require('./TheaterMasks').default
    case 'Thermometer': return require('./Thermometer').default
    case 'Thermostat': return require('./Thermostat').default
    case 'ThumbsDown': return require('./ThumbsDown').default
    case 'ThumbsUp': return require('./ThumbsUp').default
    case 'Thumbtack': return require('./Thumbtack').default
    case 'Tick': return require('./Tick').default
    case 'Ticket': return require('./Ticket').default
    case 'Timer': return require('./Timer').default
    case 'ToggleOff': return require('./ToggleOff').default
    case 'ToggleOn': return require('./ToggleOn').default
    case 'Toolbox': return require('./Toolbox').default
    case 'Tooth': return require('./Tooth').default
    case 'TrafficLight': return require('./TrafficLight').default
    case 'Train': return require('./Train').default
    case 'Trash': return require('./Trash').default
    case 'Tree': return require('./Tree').default
    case 'TrendingDown': return require('./TrendingDown').default
    case 'TrendingUp': return require('./TrendingUp').default
    case 'TriangleDown': return require('./TriangleDown').default
    case 'Triangle': return require('./Triangle').default
    case 'Trophy': return require('./Trophy').default
    case 'Truck': return require('./Truck').default
    case 'Tv': return require('./Tv').default
    case 'Umbrella': return require('./Umbrella').default
    case 'Undo': return require('./Undo').default
    case 'Unlink': return require('./Unlink').default
    case 'Unlock': return require('./Unlock').default
    case 'Upload': return require('./Upload').default
    case 'UserCircle': return require('./UserCircle').default
    case 'Utensils': return require('./Utensils').default
    case 'Vault': return require('./Vault').default
    case 'Venus': return require('./Venus').default
    case 'Video': return require('./Video').default
    case 'VolumeOff': return require('./VolumeOff').default
    case 'Volume': return require('./Volume').default
    case 'Wallet': return require('./Wallet').default
    case 'Warning': return require('./Warning').default
    case 'Washer': return require('./Washer').default
    case 'Watch': return require('./Watch').default
    case 'Waves': return require('./Waves').default
    case 'WeightScale': return require('./WeightScale').default
    case 'Wheelchair': return require('./Wheelchair').default
    case 'Wifi': return require('./Wifi').default
    case 'Wind': return require('./Wind').default
    case 'Wine': return require('./Wine').default
    case 'Wrench': return require('./Wrench').default
    case 'XCircle': return require('./XCircle').default
    case 'Yen': return require('./Yen').default
    default: return null
  }
}
