import type { GlyphName } from '../types/components'

export const GlyphCategories: Record<string, readonly GlyphName[]> = {
  'Original & alchemical': [
    'mercury', 'sulfur', 'salt', 'sun', 'moon', 'star', 'sigil', 'flask', 'key',
    'leaf', 'sprig', 'fern', 'compass', 'eye', 'hand', 'feather', 'book', 'scroll',
    'asterism', 'flourish',
  ],
  'Geometric': [
    'triangle', 'triangle-down', 'square', 'circle', 'hex', 'cross', 'tick', 'plus', 'minus',
  ],
  'Navigation': [
    'arrow-up', 'arrow-right', 'arrow-left', 'arrow-down', 'arrow-up-right', 'arrow-down-right',
    'chevron-left', 'chevron-right', 'chevron-up', 'chevron-down', 'chevrons-left', 'chevrons-right',
    'caret-down', 'caret-up', 'caret-left', 'caret-right',
    'menu', 'close', 'expand', 'collapse', 'external-link',
    'grid', 'list', 'columns', 'sidebar', 'more', 'more-vertical',
    'filter', 'sort', 'refresh', 'undo', 'redo', 'home', 'maximize', 'drag', 'search',
  ],
  'Controls & status': [
    'edit', 'pencil', 'eraser', 'trash', 'save', 'copy', 'clipboard',
    'download', 'upload', 'share', 'link', 'unlink', 'lock', 'unlock',
    'pin', 'thumbtack', 'bookmark', 'flag', 'tag',
    'check-circle', 'x-circle', 'plus-circle', 'minus-circle',
    'info', 'help', 'warning', 'ban',
    'sliders', 'toggle-on', 'toggle-off', 'eye-off', 'settings',
  ],
  'Communication': [
    'mail', 'mail-open', 'send', 'chat', 'chat-dots', 'comments',
    'phone', 'at-sign', 'inbox', 'megaphone', 'rss', 'bell', 'bell-off', 'paperclip',
  ],
  'Media & devices': [
    'play', 'pause', 'stop', 'skip-forward', 'skip-back', 'play-circle',
    'volume', 'volume-off', 'mic', 'mic-off',
    'camera', 'video', 'image', 'music-note', 'headphones', 'film',
    'monitor', 'smartphone', 'laptop', 'keyboard', 'printer',
    'battery', 'wifi', 'plug', 'cpu', 'database', 'server', 'hard-drive', 'tv', 'router',
  ],
  'Time': [
    'clock', 'calendar', 'calendar-check', 'timer', 'hourglass', 'history', 'alarm', 'sunrise',
  ],
  'Weather & nature': [
    'cloud', 'cloud-rain', 'cloud-sun', 'snowflake', 'bolt', 'wind', 'droplet', 'waves', 'fire',
    'mountain', 'tree', 'flower', 'sprout', 'umbrella', 'paw', 'bug', 'bird', 'fish',
    'acorn', 'rainbow', 'palm-tree', 'cactus', 'mushroom', 'campfire', 'snowman',
  ],
  'Transport & travel': [
    'car', 'bus', 'train', 'plane', 'ship', 'bike', 'scooter', 'truck', 'taxi',
    'fuel', 'parking', 'traffic-light', 'luggage', 'passport', 'anchor', 'road',
  ],
  'Tools & workshop': [
    'hammer', 'wrench', 'screwdriver', 'scissors', 'ruler', 'brush', 'palette',
    'gear', 'anvil', 'axe', 'pickaxe', 'shovel', 'saw', 'drafting-compass',
    'magnet', 'needle', 'toolbox', 'nut-bolt', 'gavel',
  ],
  'Shopping & apparel': [
    'shirt', 'dress', 'shoe', 'hat', 'watch', 'ring', 'glasses', 'sunglasses',
    'perfume', 'lipstick', 'hanger', 'basket', 'barcode', 'gem', 'backpack',
  ],
  'Commerce & data': [
    'cart', 'bag', 'wallet', 'credit-card', 'coin', 'receipt', 'gift',
    'chart-bar', 'chart-line', 'chart-pie', 'trending-up', 'trending-down',
    'scale', 'target', 'percent', 'box', 'archive',
  ],
  'Finance & money': [
    'bank', 'piggy-bank', 'dollar', 'euro', 'pound', 'yen', 'bitcoin', 'atm',
    'vault', 'calculator', 'money-bill', 'coins', 'hand-coin', 'exchange',
  ],
  'Home & utilities': [
    'couch', 'bed', 'lamp', 'door', 'broom', 'washer', 'thermometer', 'thermostat',
    'fire-extinguisher', 'key-round',
  ],
  'Health & fitness': [
    'dumbbell', 'heart-pulse', 'pill', 'syringe', 'stethoscope', 'tooth', 'bandage',
    'first-aid', 'lotus', 'running', 'weight-scale', 'wheelchair', 'mask', 'brain',
  ],
  'Food & drink': [
    'coffee', 'cup', 'wine', 'bottle', 'cocktail', 'cake', 'restaurant', 'utensils',
    'apple', 'ice-cream', 'bread', 'burger', 'pizza', 'noodles', 'sushi', 'taco',
    'salad', 'egg', 'donut', 'cookie', 'candy', 'popcorn', 'beer', 'soda', 'milk', 'croissant',
  ],
  'People & places': [
    'person', 'people', 'person-add', 'user-circle', 'building', 'store',
    'map', 'navigation', 'globe', 'school', 'briefcase', 'factory', 'hospital', 'tent', 'ticket',
  ],
  'Family & pets': [
    'dog', 'cat', 'bone', 'stroller', 'baby-bottle', 'teddy', 'blocks',
  ],
  'Leisure': [
    'gamepad', 'dice', 'theater-masks', 'guitar', 'piano', 'chess', 'clapperboard', 'balloon',
  ],
  'Alchemical & esoteric': [
    'venus', 'mars', 'element-fire', 'element-water', 'element-air', 'element-earth',
    'quintessence', 'ankh', 'crystal', 'candle', 'mortar-pestle', 'planet', 'comet',
    'skull', 'potion', 'scales', 'hexagram',
  ],
  'Objects & misc': [
    'heart', 'heart-filled', 'star-filled', 'thumbs-up', 'thumbs-down', 'award', 'trophy',
    'rocket', 'crown', 'shield', 'shield-check', 'lightbulb', 'puzzle', 'layers',
    'folder', 'folder-open', 'file', 'file-plus', 'note', 'shield-key',
    'crosshair', 'qr', 'fingerprint', 'fish-hook',
  ],
  'Sigils': [
    'sigil-blade', 'sigil-cardinal', 'sigil-eye', 'sigil-feather', 'sigil-flame', 'sigil-flask',
    'sigil-heptagram', 'sigil-hexnested', 'sigil-key', 'sigil-leaf', 'sigil-moon', 'sigil-octagram',
    'sigil-pentagram', 'sigil-solomon', 'sigil-spiralsquare', 'sigil-triquetra', 'sigil-vesica', 'sigil-wheel',
  ],
}

export type GlyphCategory = keyof typeof GlyphCategories

export const GlyphAliases: Partial<Record<GlyphName, readonly string[]>> = {
  'mercury': ['quicksilver', 'hydrargyrum', 'planet', 'metal', 'element'],
  'sulfur': ['brimstone', 'alchemy', 'element', 'sulphur'],
  'salt': ['alchemy', 'element', 'mineral'],
  'sun': ['solar', 'day', 'daylight', 'light', 'sunny', 'gold'],
  'moon': ['lunar', 'night', 'crescent', 'silver', 'phase'],
  'star': ['favorite', 'favourite', 'rating', 'night', 'sparkle', 'asterisk'],
  'sigil': ['seal', 'rune', 'mark', 'symbol', 'glyph', 'occult'],
  'flask': ['lab', 'laboratory', 'potion', 'chemistry', 'science', 'beaker', 'alchemy'],
  'key': ['unlock', 'password', 'access', 'login', 'secret'],
  'leaf': ['nature', 'plant', 'foliage', 'eco', 'autumn', 'herb'],
  'sprig': ['herb', 'plant', 'twig', 'botanical', 'garnish'],
  'fern': ['plant', 'frond', 'botanical', 'forest'],
  'compass': ['navigate', 'direction', 'explore', 'orient', 'map'],
  'eye': ['view', 'see', 'watch', 'visible', 'look', 'vision', 'preview'],
  'hand': ['palm', 'wave', 'touch', 'gesture'],
  'feather': ['quill', 'write', 'light', 'bird', 'plume'],
  'book': ['read', 'library', 'journal', 'notebook', 'manual', 'docs', 'guide'],
  'scroll': ['document', 'parchment', 'manuscript', 'certificate', 'deed'],
  'asterism': ['divider', 'ornament', 'marginalia', 'dots', 'three'],
  'flourish': ['divider', 'ornament', 'marginalia', 'decoration'],
  'triangle': ['up', 'play', 'warning', 'delta', 'shape'],
  'triangle-down': ['down', 'caret', 'delta', 'shape'],
  'square': ['stop', 'box', 'shape', 'checkbox'],
  'circle': ['dot', 'round', 'shape', 'ring'],
  'hex': ['hexagon', 'shape', 'honeycomb'],
  'cross': ['x', 'close', 'multiply', 'plus'],
  'tick': ['check', 'done', 'yes', 'correct', 'confirm', 'ok'],
  'plus': ['add', 'new', 'create', 'more', 'increment'],
  'minus': ['subtract', 'remove', 'decrement', 'less', 'dash'],
  'arrow-up': ['north', 'up', 'top', 'increase'],
  'arrow-right': ['next', 'forward', 'east', 'go'],
  'arrow-left': ['back', 'previous', 'prev', 'west', 'return'],
  'arrow-down': ['south', 'down', 'bottom', 'decrease'],
  'arrow-up-right': ['northeast', 'external', 'outbound', 'diagonal'],
  'arrow-down-right': ['southeast', 'inbound', 'diagonal'],
  'chevron-left': ['back', 'previous', 'prev', 'collapse'],
  'chevron-right': ['next', 'forward', 'expand', 'more'],
  'chevron-up': ['collapse', 'up', 'less'],
  'chevron-down': ['expand', 'down', 'dropdown', 'more'],
  'chevrons-left': ['first', 'rewind', 'skip', 'start'],
  'chevrons-right': ['last', 'fast', 'skip', 'end'],
  'caret-down': ['dropdown', 'expand', 'select', 'triangle'],
  'caret-up': ['collapse', 'triangle'],
  'caret-left': ['previous', 'triangle'],
  'caret-right': ['next', 'play', 'triangle'],
  'menu': ['hamburger', 'nav', 'list', 'bars', 'options'],
  'close': ['x', 'cancel', 'dismiss', 'remove', 'exit'],
  'expand': ['fullscreen', 'enlarge', 'grow', 'maximize'],
  'collapse': ['minimize', 'shrink', 'reduce'],
  'external-link': ['open', 'outbound', 'new tab', 'launch', 'visit'],
  'grid': ['layout', 'tiles', 'gallery', 'apps', 'dashboard'],
  'list': ['rows', 'lines', 'agenda', 'bullets', 'menu'],
  'columns': ['layout', 'split', 'board', 'kanban'],
  'sidebar': ['panel', 'drawer', 'layout', 'nav'],
  'more': ['ellipsis', 'options', 'overflow', 'menu', 'dots'],
  'more-vertical': ['ellipsis', 'options', 'overflow', 'kebab', 'dots'],
  'filter': ['funnel', 'refine', 'sort', 'sift'],
  'sort': ['order', 'arrange', 'rank', 'sequence'],
  'refresh': ['reload', 'sync', 'update', 'renew', 'retry'],
  'undo': ['back', 'revert', 'history'],
  'redo': ['forward', 'repeat', 'again'],
  'home': ['house', 'main', 'start', 'dashboard'],
  'maximize': ['fullscreen', 'expand', 'enlarge'],
  'drag': ['move', 'reorder', 'handle', 'grip', 'dots'],
  'search': ['find', 'magnifier', 'lookup', 'zoom', 'explore', 'look'],
  'edit': ['pencil', 'write', 'modify', 'change', 'compose'],
  'pencil': ['edit', 'write', 'draw', 'compose'],
  'eraser': ['delete', 'remove', 'rubber', 'clear'],
  'trash': ['delete', 'bin', 'remove', 'garbage', 'discard'],
  'save': ['disk', 'floppy', 'store', 'keep'],
  'copy': ['duplicate', 'clone', 'clipboard'],
  'clipboard': ['paste', 'copy', 'board', 'tasks'],
  'download': ['save', 'import', 'get', 'arrow'],
  'upload': ['export', 'send', 'arrow', 'publish'],
  'share': ['network', 'send', 'social', 'distribute'],
  'link': ['chain', 'url', 'connect', 'attach', 'hyperlink'],
  'unlink': ['break', 'disconnect', 'detach'],
  'lock': ['secure', 'private', 'locked', 'password', 'closed'],
  'unlock': ['open', 'access', 'unsecure'],
  'pin': ['location', 'marker', 'place', 'map', 'tack'],
  'thumbtack': ['pin', 'attach', 'board', 'tack'],
  'bookmark': ['save', 'favorite', 'favourite', 'ribbon', 'later'],
  'flag': ['report', 'milestone', 'country', 'mark'],
  'tag': ['label', 'price', 'category', 'badge'],
  'check-circle': ['done', 'success', 'complete', 'verified', 'ok', 'approve'],
  'x-circle': ['error', 'cancel', 'fail', 'remove', 'close'],
  'plus-circle': ['add', 'new', 'create', 'include'],
  'minus-circle': ['remove', 'subtract', 'exclude'],
  'info': ['information', 'about', 'details', 'help', 'tooltip'],
  'help': ['question', 'support', 'faq', 'ask'],
  'warning': ['caution', 'alert', 'danger', 'attention'],
  'ban': ['block', 'forbidden', 'no', 'prohibited', 'denied'],
  'sliders': ['settings', 'controls', 'adjust', 'filters', 'mixer', 'tune'],
  'toggle-on': ['switch', 'enabled', 'active', 'on'],
  'toggle-off': ['switch', 'disabled', 'inactive', 'off'],
  'eye-off': ['hide', 'hidden', 'invisible', 'private', 'conceal'],
  'settings': ['gear', 'cog', 'preferences', 'options', 'config'],
  'mail': ['email', 'envelope', 'message', 'inbox', 'letter', 'contact'],
  'mail-open': ['email', 'read', 'opened', 'envelope'],
  'send': ['paper plane', 'submit', 'message', 'deliver'],
  'chat': ['message', 'talk', 'bubble', 'comment', 'sms'],
  'chat-dots': ['message', 'typing', 'talk', 'bubble'],
  'comments': ['discussion', 'replies', 'thread', 'talk'],
  'phone': ['call', 'telephone', 'contact', 'mobile', 'ring'],
  'at-sign': ['email', 'mention', 'handle', 'username'],
  'inbox': ['mail', 'messages', 'receive', 'tray'],
  'megaphone': ['announce', 'broadcast', 'marketing', 'promote', 'loud', 'bullhorn'],
  'rss': ['feed', 'subscribe', 'news', 'syndicate'],
  'bell': ['notification', 'alert', 'reminder', 'ring', 'alarm'],
  'bell-off': ['mute', 'silent', 'do not disturb', 'notification'],
  'paperclip': ['attach', 'attachment', 'clip', 'file'],
  'play': ['start', 'video', 'media', 'run', 'begin'],
  'pause': ['stop', 'hold', 'break', 'media'],
  'stop': ['end', 'square', 'halt', 'media'],
  'skip-forward': ['next', 'fast', 'forward', 'media'],
  'skip-back': ['previous', 'rewind', 'back', 'media'],
  'play-circle': ['start', 'video', 'watch', 'media'],
  'volume': ['sound', 'speaker', 'audio', 'loud'],
  'volume-off': ['mute', 'silent', 'sound', 'quiet'],
  'mic': ['microphone', 'record', 'audio', 'voice', 'speak'],
  'mic-off': ['mute', 'microphone', 'silent', 'muted'],
  'camera': ['photo', 'picture', 'capture', 'snapshot'],
  'video': ['camera', 'film', 'record', 'movie', 'recording'],
  'image': ['photo', 'picture', 'gallery', 'media', 'pic'],
  'music-note': ['song', 'audio', 'melody', 'tune', 'sound'],
  'headphones': ['audio', 'music', 'sound', 'listen', 'headset'],
  'film': ['movie', 'video', 'cinema', 'reel', 'media'],
  'monitor': ['screen', 'display', 'desktop', 'computer', 'tv'],
  'smartphone': ['phone', 'mobile', 'cell', 'device'],
  'laptop': ['computer', 'notebook', 'device', 'macbook'],
  'keyboard': ['type', 'keys', 'input', 'typing'],
  'printer': ['print', 'document', 'paper', 'office'],
  'battery': ['power', 'charge', 'energy', 'level'],
  'wifi': ['wireless', 'internet', 'network', 'signal', 'connection'],
  'plug': ['power', 'charge', 'connect', 'outlet', 'electric'],
  'cpu': ['processor', 'chip', 'compute', 'hardware'],
  'database': ['storage', 'data', 'server', 'db', 'records'],
  'server': ['hosting', 'rack', 'data', 'backend', 'cloud'],
  'hard-drive': ['storage', 'disk', 'hdd', 'data', 'memory'],
  'tv': ['television', 'screen', 'monitor', 'watch', 'display'],
  'router': ['wifi', 'network', 'modem', 'internet', 'wireless'],
  'clock': ['time', 'schedule', 'watch', 'hour', 'wait'],
  'calendar': ['date', 'schedule', 'event', 'month', 'planner'],
  'calendar-check': ['scheduled', 'appointment', 'booked', 'done', 'event'],
  'timer': ['stopwatch', 'countdown', 'time', 'duration'],
  'hourglass': ['time', 'wait', 'loading', 'sand', 'timer'],
  'history': ['recent', 'past', 'log', 'undo', 'clock', 'activity'],
  'alarm': ['clock', 'wake', 'reminder', 'time'],
  'sunrise': ['morning', 'dawn', 'sun', 'sunset', 'horizon'],
  'cloud': ['weather', 'cloudy', 'sky', 'overcast', 'storage'],
  'cloud-rain': ['weather', 'rainy', 'storm', 'precipitation', 'wet'],
  'cloud-sun': ['weather', 'partly cloudy', 'forecast', 'day'],
  'snowflake': ['snow', 'winter', 'cold', 'freeze', 'ice', 'frost'],
  'bolt': ['lightning', 'thunder', 'flash', 'electric', 'power', 'storm', 'energy'],
  'wind': ['breeze', 'air', 'windy', 'weather', 'gust'],
  'droplet': ['water', 'drop', 'liquid', 'rain', 'moisture', 'wet'],
  'waves': ['water', 'sea', 'ocean', 'tide', 'ripple'],
  'fire': ['flame', 'heat', 'hot', 'burn', 'campfire', 'warm', 'spicy'],
  'mountain': ['hill', 'peak', 'summit', 'outdoor', 'hike', 'nature'],
  'tree': ['nature', 'forest', 'plant', 'wood', 'park', 'pine'],
  'flower': ['bloom', 'blossom', 'plant', 'garden', 'floral', 'nature'],
  'sprout': ['seedling', 'plant', 'grow', 'eco', 'germinate', 'garden'],
  'umbrella': ['rain', 'weather', 'parasol', 'protection', 'insurance'],
  'paw': ['pet', 'animal', 'dog', 'cat', 'print', 'track'],
  'bug': ['insect', 'beetle', 'error', 'pest', 'debug'],
  'bird': ['animal', 'tweet', 'sparrow', 'fly', 'nature'],
  'fish': ['animal', 'sea', 'seafood', 'aquarium', 'swim'],
  'acorn': ['nut', 'oak', 'autumn', 'seed', 'fall', 'squirrel'],
  'rainbow': ['weather', 'pride', 'colors', 'arc', 'spectrum'],
  'palm-tree': ['tropical', 'beach', 'vacation', 'holiday', 'coconut', 'island'],
  'cactus': ['desert', 'plant', 'succulent', 'southwest', 'spike'],
  'mushroom': ['fungus', 'toadstool', 'forage', 'plant', 'fungi'],
  'campfire': ['fire', 'camp', 'bonfire', 'outdoor', 'flame'],
  'snowman': ['winter', 'snow', 'christmas', 'cold', 'frosty'],
  'car': ['auto', 'vehicle', 'drive', 'automobile', 'sedan', 'transport'],
  'bus': ['transit', 'coach', 'transport', 'public', 'shuttle'],
  'train': ['rail', 'metro', 'subway', 'transit', 'locomotive', 'transport'],
  'plane': ['airplane', 'flight', 'fly', 'airport', 'travel', 'aircraft', 'aviation'],
  'ship': ['boat', 'sail', 'cruise', 'ferry', 'vessel', 'sea', 'maritime'],
  'bike': ['bicycle', 'cycle', 'cycling', 'ride', 'pedal'],
  'scooter': ['moped', 'vespa', 'ride', 'kick'],
  'truck': ['lorry', 'delivery', 'freight', 'cargo', 'shipping', 'haul'],
  'taxi': ['cab', 'uber', 'ride', 'hail', 'transport'],
  'fuel': ['gas', 'petrol', 'station', 'gasoline', 'pump', 'energy'],
  'parking': ['park', 'garage', 'lot', 'car'],
  'traffic-light': ['signal', 'stoplight', 'traffic', 'intersection'],
  'luggage': ['suitcase', 'baggage', 'travel', 'trip', 'bag'],
  'passport': ['travel', 'id', 'visa', 'identity', 'document', 'border'],
  'anchor': ['boat', 'ship', 'nautical', 'marine', 'sea', 'harbor'],
  'road': ['street', 'highway', 'route', 'path', 'drive', 'journey'],
  'hammer': ['tool', 'build', 'construct', 'nail', 'repair', 'hardware'],
  'wrench': ['tool', 'spanner', 'fix', 'repair', 'mechanic', 'settings'],
  'screwdriver': ['tool', 'screw', 'fix', 'repair', 'assemble'],
  'scissors': ['cut', 'trim', 'snip', 'shears', 'clip'],
  'ruler': ['measure', 'scale', 'length', 'straight', 'dimensions'],
  'brush': ['paint', 'art', 'stroke', 'design', 'clean'],
  'palette': ['color', 'paint', 'art', 'swatch', 'design', 'theme'],
  'gear': ['settings', 'cog', 'mechanism', 'config', 'machine'],
  'anvil': ['forge', 'blacksmith', 'metal', 'smith', 'workshop'],
  'axe': ['chop', 'wood', 'hatchet', 'lumber', 'cut'],
  'pickaxe': ['mine', 'dig', 'mining', 'pick', 'quarry'],
  'shovel': ['dig', 'spade', 'garden', 'excavate', 'dirt'],
  'saw': ['cut', 'wood', 'carpentry', 'blade', 'lumber'],
  'drafting-compass': ['draw', 'geometry', 'circle', 'technical', 'architect'],
  'magnet': ['magnetic', 'attract', 'field', 'physics', 'pull'],
  'needle': ['sew', 'thread', 'stitch', 'sharp', 'tailor'],
  'toolbox': ['tools', 'kit', 'repair', 'hardware', 'equipment'],
  'nut-bolt': ['hardware', 'fastener', 'screw', 'mechanic', 'assembly'],
  'gavel': ['judge', 'law', 'court', 'auction', 'legal', 'justice', 'hammer'],
  'shirt': ['clothes', 'apparel', 'tshirt', 'top', 'tee', 'fashion', 'clothing'],
  'dress': ['clothes', 'apparel', 'fashion', 'gown', 'women', 'clothing'],
  'shoe': ['footwear', 'sneaker', 'boot', 'fashion', 'clothing'],
  'hat': ['cap', 'clothing', 'fashion', 'headwear', 'accessory'],
  'watch': ['time', 'clock', 'wrist', 'accessory', 'wearable'],
  'ring': ['jewelry', 'wedding', 'engagement', 'band', 'diamond'],
  'glasses': ['spectacles', 'eyewear', 'vision', 'reading', 'optical'],
  'sunglasses': ['shades', 'eyewear', 'sun', 'summer', 'cool'],
  'perfume': ['fragrance', 'cologne', 'scent', 'beauty', 'cosmetics'],
  'lipstick': ['makeup', 'cosmetics', 'beauty', 'lips'],
  'hanger': ['clothes', 'closet', 'wardrobe', 'hang', 'laundry'],
  'basket': ['shopping', 'grocery', 'cart', 'market', 'buy'],
  'barcode': ['scan', 'product', 'sku', 'price', 'upc'],
  'gem': ['jewel', 'diamond', 'gemstone', 'precious', 'crystal', 'luxury'],
  'backpack': ['bag', 'rucksack', 'school', 'travel', 'hike'],
  'cart': ['shopping', 'buy', 'checkout', 'basket', 'ecommerce', 'trolley'],
  'bag': ['shopping', 'purchase', 'tote', 'buy', 'handbag'],
  'wallet': ['money', 'payment', 'cash', 'billfold', 'finance'],
  'credit-card': ['payment', 'debit', 'card', 'pay', 'bank', 'checkout'],
  'coin': ['money', 'cash', 'currency', 'token', 'payment'],
  'receipt': ['invoice', 'bill', 'purchase', 'transaction', 'order'],
  'gift': ['present', 'reward', 'box', 'birthday', 'bonus'],
  'chart-bar': ['graph', 'analytics', 'statistics', 'data', 'bars', 'report'],
  'chart-line': ['graph', 'analytics', 'trend', 'data', 'line', 'report'],
  'chart-pie': ['graph', 'analytics', 'statistics', 'data', 'pie', 'breakdown'],
  'trending-up': ['growth', 'increase', 'rise', 'up', 'gain', 'profit'],
  'trending-down': ['decline', 'decrease', 'drop', 'down', 'loss', 'fall'],
  'scale': ['balance', 'justice', 'weigh', 'compare', 'law'],
  'target': ['goal', 'aim', 'bullseye', 'objective', 'focus', 'accuracy'],
  'percent': ['discount', 'sale', 'rate', 'percentage', 'off'],
  'box': ['package', 'parcel', 'shipping', 'cube', 'product', '3d'],
  'archive': ['store', 'box', 'backup', 'old', 'file', 'storage'],
  'bank': ['finance', 'money', 'institution', 'building', 'account', 'savings'],
  'piggy-bank': ['savings', 'save', 'money', 'deposit', 'budget', 'funds'],
  'dollar': ['money', 'usd', 'currency', 'cash', 'price', 'payment'],
  'euro': ['money', 'eur', 'currency', 'europe', 'cash'],
  'pound': ['money', 'gbp', 'currency', 'sterling', 'britain', 'cash'],
  'yen': ['money', 'jpy', 'currency', 'japan', 'yuan', 'cash'],
  'bitcoin': ['crypto', 'btc', 'currency', 'blockchain', 'digital', 'money'],
  'atm': ['cash', 'machine', 'withdraw', 'bank', 'money'],
  'vault': ['safe', 'secure', 'bank', 'storage', 'money', 'deposit'],
  'calculator': ['math', 'compute', 'accounting', 'numbers', 'sum'],
  'money-bill': ['cash', 'dollar', 'note', 'currency', 'payment'],
  'coins': ['money', 'cash', 'change', 'currency', 'savings', 'stack'],
  'hand-coin': ['payment', 'give', 'donate', 'tip', 'salary', 'income', 'pay'],
  'exchange': ['transfer', 'swap', 'convert', 'trade', 'currency'],
  'couch': ['sofa', 'furniture', 'living room', 'seat', 'lounge'],
  'bed': ['sleep', 'bedroom', 'furniture', 'rest', 'hotel'],
  'lamp': ['light', 'desk', 'furniture', 'lighting', 'bulb'],
  'door': ['entrance', 'exit', 'room', 'open', 'enter'],
  'broom': ['clean', 'sweep', 'chores', 'housekeeping', 'tidy'],
  'washer': ['laundry', 'washing machine', 'clean', 'appliance'],
  'thermometer': ['temperature', 'fever', 'heat', 'weather', 'health'],
  'thermostat': ['temperature', 'heating', 'climate', 'nest', 'hvac'],
  'fire-extinguisher': ['safety', 'fire', 'emergency', 'protect'],
  'key-round': ['unlock', 'password', 'access', 'login', 'key', 'security'],
  'dumbbell': ['gym', 'workout', 'weights', 'exercise', 'fitness', 'lift', 'muscle'],
  'heart-pulse': ['health', 'heartbeat', 'cardio', 'medical', 'vitals', 'ecg'],
  'pill': ['medicine', 'drug', 'pharmacy', 'medication', 'tablet', 'health'],
  'syringe': ['injection', 'vaccine', 'needle', 'medical', 'shot', 'health'],
  'stethoscope': ['doctor', 'medical', 'health', 'checkup', 'clinic'],
  'tooth': ['dental', 'dentist', 'teeth', 'oral', 'health'],
  'bandage': ['plaster', 'injury', 'first aid', 'wound', 'medical', 'heal'],
  'first-aid': ['medical', 'emergency', 'kit', 'health', 'help', 'aid'],
  'lotus': ['yoga', 'meditation', 'zen', 'wellness', 'flower', 'spa', 'calm'],
  'running': ['run', 'jog', 'exercise', 'fitness', 'marathon', 'sprint', 'cardio'],
  'weight-scale': ['weigh', 'bathroom scale', 'fitness', 'health', 'measure'],
  'wheelchair': ['accessible', 'disability', 'accessibility', 'handicap', 'mobility'],
  'mask': ['face mask', 'medical', 'covid', 'protection', 'health'],
  'brain': ['mind', 'think', 'memory', 'neuroscience', 'intelligence', 'mental'],
  'coffee': ['cafe', 'drink', 'espresso', 'latte', 'mug', 'caffeine', 'tea'],
  'cup': ['drink', 'mug', 'beverage', 'tea', 'glass'],
  'wine': ['drink', 'alcohol', 'glass', 'bar', 'vineyard', 'merlot'],
  'bottle': ['drink', 'water', 'container', 'beverage'],
  'cocktail': ['drink', 'bar', 'alcohol', 'martini', 'mixer', 'party'],
  'cake': ['dessert', 'birthday', 'bakery', 'sweet', 'celebration', 'pastry'],
  'restaurant': ['food', 'dining', 'eat', 'fork', 'knife', 'meal', 'cutlery'],
  'utensils': ['fork', 'spoon', 'cutlery', 'eat', 'dining', 'silverware'],
  'apple': ['fruit', 'food', 'healthy', 'snack', 'orchard'],
  'ice-cream': ['dessert', 'sweet', 'cone', 'gelato', 'summer', 'frozen'],
  'bread': ['bakery', 'loaf', 'food', 'toast', 'carbs'],
  'burger': ['food', 'fast food', 'hamburger', 'sandwich', 'beef', 'meal'],
  'pizza': ['food', 'italian', 'slice', 'fast food', 'pepperoni', 'meal'],
  'noodles': ['food', 'ramen', 'pasta', 'asian', 'soup', 'bowl'],
  'sushi': ['food', 'japanese', 'seafood', 'roll', 'asian'],
  'taco': ['food', 'mexican', 'burrito', 'wrap', 'fast food'],
  'salad': ['food', 'healthy', 'vegetables', 'greens', 'vegan', 'bowl'],
  'egg': ['food', 'breakfast', 'protein', 'omelette', 'easter'],
  'donut': ['doughnut', 'dessert', 'sweet', 'pastry', 'bakery', 'snack'],
  'cookie': ['biscuit', 'dessert', 'sweet', 'snack', 'bakery', 'treat'],
  'candy': ['sweet', 'sugar', 'treat', 'confectionery', 'dessert'],
  'popcorn': ['snack', 'cinema', 'movie', 'corn', 'treat'],
  'beer': ['drink', 'alcohol', 'pub', 'bar', 'pint', 'ale', 'lager'],
  'soda': ['drink', 'cola', 'pop', 'fizzy', 'soft drink', 'beverage'],
  'milk': ['drink', 'dairy', 'carton', 'beverage', 'breakfast'],
  'croissant': ['pastry', 'bakery', 'breakfast', 'french', 'food'],
  'person': ['user', 'profile', 'account', 'people', 'human', 'individual', 'avatar'],
  'people': ['users', 'group', 'team', 'community', 'persons', 'crowd'],
  'person-add': ['add user', 'invite', 'signup', 'register', 'follow', 'new contact'],
  'user-circle': ['profile', 'account', 'avatar', 'user', 'contact'],
  'building': ['office', 'company', 'business', 'city', 'apartment', 'tower'],
  'store': ['shop', 'retail', 'market', 'business', 'storefront', 'merchant'],
  'map': ['location', 'navigation', 'directions', 'travel', 'geography'],
  'navigation': ['compass', 'direction', 'gps', 'arrow', 'navigate', 'locate'],
  'globe': ['world', 'earth', 'international', 'web', 'global', 'language'],
  'school': ['education', 'university', 'college', 'learn', 'academy', 'student'],
  'briefcase': ['work', 'business', 'job', 'office', 'portfolio', 'career'],
  'factory': ['industry', 'manufacturing', 'plant', 'production', 'industrial'],
  'hospital': ['medical', 'health', 'clinic', 'emergency', 'care'],
  'tent': ['camp', 'camping', 'outdoor', 'festival', 'shelter'],
  'ticket': ['event', 'admission', 'pass', 'voucher', 'coupon', 'entry'],
  'dog': ['pet', 'animal', 'puppy', 'canine', 'hound'],
  'cat': ['pet', 'animal', 'kitten', 'feline', 'kitty'],
  'bone': ['dog', 'pet', 'treat', 'skeleton', 'chew'],
  'stroller': ['baby', 'pram', 'child', 'infant', 'buggy', 'parenting'],
  'baby-bottle': ['baby', 'infant', 'milk', 'feed', 'child', 'nursery'],
  'teddy': ['toy', 'bear', 'child', 'plush', 'kids'],
  'blocks': ['toy', 'kids', 'building', 'child', 'play', 'lego'],
  'gamepad': ['game', 'controller', 'gaming', 'console', 'play', 'joystick'],
  'dice': ['game', 'random', 'chance', 'board game', 'luck', 'roll'],
  'theater-masks': ['drama', 'comedy', 'tragedy', 'acting', 'performance', 'arts'],
  'guitar': ['music', 'instrument', 'band', 'rock', 'strings'],
  'piano': ['music', 'instrument', 'keys', 'keyboard', 'classical'],
  'chess': ['game', 'strategy', 'board game', 'pawn', 'play'],
  'clapperboard': ['movie', 'film', 'video', 'director', 'production', 'cinema'],
  'balloon': ['party', 'celebration', 'birthday', 'festive', 'float'],
  'venus': ['female', 'woman', 'feminine', 'copper', 'planet', 'gender'],
  'mars': ['male', 'man', 'masculine', 'iron', 'planet', 'gender'],
  'element-fire': ['alchemy', 'triangle', 'classical element', 'hot'],
  'element-water': ['alchemy', 'triangle', 'classical element', 'liquid'],
  'element-air': ['alchemy', 'triangle', 'classical element', 'wind'],
  'element-earth': ['alchemy', 'triangle', 'classical element', 'ground'],
  'quintessence': ['aether', 'fifth element', 'spirit', 'essence', 'occult'],
  'ankh': ['egyptian', 'life', 'cross', 'eternal', 'symbol'],
  'crystal': ['gem', 'quartz', 'mineral', 'esoteric', 'healing'],
  'candle': ['flame', 'light', 'wax', 'wick', 'vigil', 'fire'],
  'mortar-pestle': ['grind', 'apothecary', 'pharmacy', 'herbs', 'potion', 'alchemy'],
  'planet': ['saturn', 'space', 'astronomy', 'ringed', 'cosmos'],
  'comet': ['space', 'astronomy', 'meteor', 'shooting star', 'cosmos'],
  'skull': ['death', 'danger', 'poison', 'bone', 'pirate', 'dead'],
  'potion': ['flask', 'elixir', 'magic', 'brew', 'alchemy', 'vial'],
  'scales': ['balance', 'justice', 'libra', 'weigh', 'law', 'fairness'],
  'hexagram': ['star of david', 'six point', 'occult', 'seal', 'symbol'],
  'heart': ['love', 'like', 'favorite', 'favourite', 'health', 'romance'],
  'heart-filled': ['love', 'like', 'favorite', 'favourite', 'liked', 'solid'],
  'star-filled': ['favorite', 'favourite', 'rating', 'rated', 'solid', 'bookmark'],
  'thumbs-up': ['like', 'approve', 'good', 'yes', 'upvote', 'positive'],
  'thumbs-down': ['dislike', 'disapprove', 'bad', 'no', 'downvote', 'negative'],
  'award': ['medal', 'prize', 'achievement', 'badge', 'winner', 'honor'],
  'trophy': ['win', 'champion', 'prize', 'award', 'first', 'victory'],
  'rocket': ['launch', 'startup', 'space', 'boost', 'fast', 'ship'],
  'crown': ['king', 'queen', 'royal', 'premium', 'vip', 'best'],
  'shield': ['security', 'protect', 'safety', 'guard', 'defense', 'privacy'],
  'shield-check': ['secure', 'verified', 'protected', 'safe', 'trusted'],
  'lightbulb': ['idea', 'tip', 'innovation', 'bright', 'insight', 'hint'],
  'puzzle': ['piece', 'plugin', 'extension', 'solve', 'jigsaw', 'integration'],
  'layers': ['stack', 'levels', 'overlap', 'z-index', 'design'],
  'folder': ['directory', 'files', 'storage', 'organize'],
  'folder-open': ['directory', 'files', 'open', 'browse'],
  'file': ['document', 'page', 'paper', 'doc'],
  'file-plus': ['new document', 'add file', 'create', 'new'],
  'note': ['memo', 'sticky', 'reminder', 'annotation', 'post-it'],
  'shield-key': ['security', 'access', 'protected', 'permission', 'vault'],
  'crosshair': ['target', 'aim', 'precision', 'focus', 'locate'],
  'qr': ['qr code', 'scan', 'barcode', 'code', 'square'],
  'fingerprint': ['biometric', 'identity', 'touch id', 'secure', 'scan', 'print'],
  'fish-hook': ['fishing', 'catch', 'angle', 'bait', 'hook'],
}

/** Human label: 'chart-bar' → 'Chart Bar'. */
export const glyphLabel = (name: GlyphName): string =>
  name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

/** Category a glyph belongs to (first match), or undefined. */
export const glyphCategory = (name: GlyphName): GlyphCategory | undefined =>
  (Object.keys(GlyphCategories) as GlyphCategory[]).find(c =>
    (GlyphCategories[c] as readonly string[]).includes(name)
  )

export interface GlyphSearchResult {
  name: GlyphName
  score: number
}

/**
 * Search glyphs by free text, ranked by relevance (higher = better).
 *
 * Multi-word queries use AND semantics — every token must hit something.
 * Returns matches sorted by score desc, then alphabetically, capped by `limit`.
 */
export const searchGlyphs = (
  query: string,
  allNames: readonly GlyphName[],
  limit = Infinity,
): GlyphSearchResult[] => {
  const q = query.trim().toLowerCase()
  if (!q) return allNames.map(name => ({ name, score: 0 }))
  const tokens = q.split(/\s+/).filter(Boolean)

  const scoreToken = (name: GlyphName, token: string): number => {
    const label = glyphLabel(name).toLowerCase()
    const words = name.split('-')
    const al = (GlyphAliases[name] as string[]) ?? []
    let best = 0

    if (name === token || label === token) best = Math.max(best, 100)
    if (name.startsWith(token) || label.startsWith(token)) best = Math.max(best, 70)
    if (words.some(w => w.startsWith(token))) best = Math.max(best, 55)
    if (name.includes(token) || label.includes(token)) best = Math.max(best, 40)

    for (let i = 0; i < al.length; i++) {
      const a = al[i]
      if (!a) continue
      const rank = Math.min(i, 9)
      if (a === token) best = Math.max(best, 100 - 2 - rank * 2)
      else if (a.startsWith(token)) best = Math.max(best, 50 - rank * 2)
      else if (a.includes(token)) best = Math.max(best, 30 - rank * 1.5)
    }
    return best
  }

  const results: GlyphSearchResult[] = []
  for (const name of allNames) {
    let total = 0
    let missed = false
    for (const token of tokens) {
      const s = scoreToken(name, token)
      if (s === 0) missed = true
      total += s
    }
    if (total > 0 && !(tokens.length > 1 && missed)) {
      results.push({ name, score: total })
    }
  }

  results.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
  return Number.isFinite(limit) ? results.slice(0, limit) : results
}
