// AUTO-GENERATED — do not edit manually. Run: node scripts/generate-glyphs.mjs
import type { ViewStyle } from 'react-native'
type GlyphFC = React.ComponentType<{ width?: number; height?: number; color?: string; style?: ViewStyle }>
export function lookupNativeGlyph(name: string): GlyphFC | null {
  switch (name) {
    case 'Acorn': return require('./svg/acorn.svg').default
    case 'Alarm': return require('./svg/alarm.svg').default
    case 'Anchor': return require('./svg/anchor.svg').default
    case 'Ankh': return require('./svg/ankh.svg').default
    case 'Anvil': return require('./svg/anvil.svg').default
    case 'Apple': return require('./svg/apple.svg').default
    case 'Archive': return require('./svg/archive.svg').default
    case 'ArrowDownRight': return require('./svg/arrow-down-right.svg').default
    case 'ArrowDown': return require('./svg/arrow-down.svg').default
    case 'ArrowLeft': return require('./svg/arrow-left.svg').default
    case 'ArrowRight': return require('./svg/arrow-right.svg').default
    case 'ArrowUpRight': return require('./svg/arrow-up-right.svg').default
    case 'ArrowUp': return require('./svg/arrow-up.svg').default
    case 'Asterism': return require('./svg/asterism.svg').default
    case 'AtSign': return require('./svg/at-sign.svg').default
    case 'Atm': return require('./svg/atm.svg').default
    case 'Award': return require('./svg/award.svg').default
    case 'Axe': return require('./svg/axe.svg').default
    case 'BabyBottle': return require('./svg/baby-bottle.svg').default
    case 'Backpack': return require('./svg/backpack.svg').default
    case 'Bag': return require('./svg/bag.svg').default
    case 'Balloon': return require('./svg/balloon.svg').default
    case 'Ban': return require('./svg/ban.svg').default
    case 'Bandage': return require('./svg/bandage.svg').default
    case 'Bank': return require('./svg/bank.svg').default
    case 'Barcode': return require('./svg/barcode.svg').default
    case 'Basket': return require('./svg/basket.svg').default
    case 'Battery': return require('./svg/battery.svg').default
    case 'Bed': return require('./svg/bed.svg').default
    case 'Beer': return require('./svg/beer.svg').default
    case 'BellOff': return require('./svg/bell-off.svg').default
    case 'Bell': return require('./svg/bell.svg').default
    case 'Bike': return require('./svg/bike.svg').default
    case 'Bird': return require('./svg/bird.svg').default
    case 'Bitcoin': return require('./svg/bitcoin.svg').default
    case 'Blocks': return require('./svg/blocks.svg').default
    case 'Bolt': return require('./svg/bolt.svg').default
    case 'Bone': return require('./svg/bone.svg').default
    case 'Book': return require('./svg/book.svg').default
    case 'Bookmark': return require('./svg/bookmark.svg').default
    case 'Bottle': return require('./svg/bottle.svg').default
    case 'Box': return require('./svg/box.svg').default
    case 'Brain': return require('./svg/brain.svg').default
    case 'Bread': return require('./svg/bread.svg').default
    case 'Briefcase': return require('./svg/briefcase.svg').default
    case 'Broom': return require('./svg/broom.svg').default
    case 'Brush': return require('./svg/brush.svg').default
    case 'Bug': return require('./svg/bug.svg').default
    case 'Building': return require('./svg/building.svg').default
    case 'Burger': return require('./svg/burger.svg').default
    case 'Bus': return require('./svg/bus.svg').default
    case 'Cactus': return require('./svg/cactus.svg').default
    case 'Cake': return require('./svg/cake.svg').default
    case 'Calculator': return require('./svg/calculator.svg').default
    case 'CalendarCheck': return require('./svg/calendar-check.svg').default
    case 'Calendar': return require('./svg/calendar.svg').default
    case 'Camera': return require('./svg/camera.svg').default
    case 'Campfire': return require('./svg/campfire.svg').default
    case 'Candle': return require('./svg/candle.svg').default
    case 'Candy': return require('./svg/candy.svg').default
    case 'Car': return require('./svg/car.svg').default
    case 'CaretDown': return require('./svg/caret-down.svg').default
    case 'CaretLeft': return require('./svg/caret-left.svg').default
    case 'CaretRight': return require('./svg/caret-right.svg').default
    case 'CaretUp': return require('./svg/caret-up.svg').default
    case 'Cart': return require('./svg/cart.svg').default
    case 'Cat': return require('./svg/cat.svg').default
    case 'ChartBar': return require('./svg/chart-bar.svg').default
    case 'ChartLine': return require('./svg/chart-line.svg').default
    case 'ChartPie': return require('./svg/chart-pie.svg').default
    case 'ChatDots': return require('./svg/chat-dots.svg').default
    case 'Chat': return require('./svg/chat.svg').default
    case 'CheckCircle': return require('./svg/check-circle.svg').default
    case 'Chess': return require('./svg/chess.svg').default
    case 'ChevronDown': return require('./svg/chevron-down.svg').default
    case 'ChevronLeft': return require('./svg/chevron-left.svg').default
    case 'ChevronRight': return require('./svg/chevron-right.svg').default
    case 'ChevronUp': return require('./svg/chevron-up.svg').default
    case 'ChevronsLeft': return require('./svg/chevrons-left.svg').default
    case 'ChevronsRight': return require('./svg/chevrons-right.svg').default
    case 'Circle': return require('./svg/circle.svg').default
    case 'Clapperboard': return require('./svg/clapperboard.svg').default
    case 'Clipboard': return require('./svg/clipboard.svg').default
    case 'Clock': return require('./svg/clock.svg').default
    case 'Close': return require('./svg/close.svg').default
    case 'CloudRain': return require('./svg/cloud-rain.svg').default
    case 'CloudSun': return require('./svg/cloud-sun.svg').default
    case 'Cloud': return require('./svg/cloud.svg').default
    case 'Cocktail': return require('./svg/cocktail.svg').default
    case 'Coffee': return require('./svg/coffee.svg').default
    case 'Coin': return require('./svg/coin.svg').default
    case 'Coins': return require('./svg/coins.svg').default
    case 'Collapse': return require('./svg/collapse.svg').default
    case 'Columns': return require('./svg/columns.svg').default
    case 'Comet': return require('./svg/comet.svg').default
    case 'Comments': return require('./svg/comments.svg').default
    case 'Compass': return require('./svg/compass.svg').default
    case 'Cookie': return require('./svg/cookie.svg').default
    case 'Copy': return require('./svg/copy.svg').default
    case 'Couch': return require('./svg/couch.svg').default
    case 'Cpu': return require('./svg/cpu.svg').default
    case 'CreditCard': return require('./svg/credit-card.svg').default
    case 'Croissant': return require('./svg/croissant.svg').default
    case 'Cross': return require('./svg/cross.svg').default
    case 'Crosshair': return require('./svg/crosshair.svg').default
    case 'Crown': return require('./svg/crown.svg').default
    case 'Crystal': return require('./svg/crystal.svg').default
    case 'Cup': return require('./svg/cup.svg').default
    case 'Database': return require('./svg/database.svg').default
    case 'Dice': return require('./svg/dice.svg').default
    case 'Dog': return require('./svg/dog.svg').default
    case 'Dollar': return require('./svg/dollar.svg').default
    case 'Donut': return require('./svg/donut.svg').default
    case 'Door': return require('./svg/door.svg').default
    case 'Download': return require('./svg/download.svg').default
    case 'DraftingCompass': return require('./svg/drafting-compass.svg').default
    case 'Drag': return require('./svg/drag.svg').default
    case 'Dress': return require('./svg/dress.svg').default
    case 'Droplet': return require('./svg/droplet.svg').default
    case 'Dumbbell': return require('./svg/dumbbell.svg').default
    case 'Edit': return require('./svg/edit.svg').default
    case 'Egg': return require('./svg/egg.svg').default
    case 'ElementAir': return require('./svg/element-air.svg').default
    case 'ElementEarth': return require('./svg/element-earth.svg').default
    case 'ElementFire': return require('./svg/element-fire.svg').default
    case 'ElementWater': return require('./svg/element-water.svg').default
    case 'Eraser': return require('./svg/eraser.svg').default
    case 'Euro': return require('./svg/euro.svg').default
    case 'Exchange': return require('./svg/exchange.svg').default
    case 'Expand': return require('./svg/expand.svg').default
    case 'ExternalLink': return require('./svg/external-link.svg').default
    case 'EyeOff': return require('./svg/eye-off.svg').default
    case 'Eye': return require('./svg/eye.svg').default
    case 'Factory': return require('./svg/factory.svg').default
    case 'Feather': return require('./svg/feather.svg').default
    case 'Fern': return require('./svg/fern.svg').default
    case 'FilePlus': return require('./svg/file-plus.svg').default
    case 'File': return require('./svg/file.svg').default
    case 'Film': return require('./svg/film.svg').default
    case 'Filter': return require('./svg/filter.svg').default
    case 'Fingerprint': return require('./svg/fingerprint.svg').default
    case 'FireExtinguisher': return require('./svg/fire-extinguisher.svg').default
    case 'Fire': return require('./svg/fire.svg').default
    case 'FirstAid': return require('./svg/first-aid.svg').default
    case 'FishHook': return require('./svg/fish-hook.svg').default
    case 'Fish': return require('./svg/fish.svg').default
    case 'Flag': return require('./svg/flag.svg').default
    case 'Flask': return require('./svg/flask.svg').default
    case 'Flourish': return require('./svg/flourish.svg').default
    case 'Flower': return require('./svg/flower.svg').default
    case 'FolderOpen': return require('./svg/folder-open.svg').default
    case 'Folder': return require('./svg/folder.svg').default
    case 'Fuel': return require('./svg/fuel.svg').default
    case 'Gamepad': return require('./svg/gamepad.svg').default
    case 'Gavel': return require('./svg/gavel.svg').default
    case 'Gear': return require('./svg/gear.svg').default
    case 'Gem': return require('./svg/gem.svg').default
    case 'Gift': return require('./svg/gift.svg').default
    case 'Glasses': return require('./svg/glasses.svg').default
    case 'Globe': return require('./svg/globe.svg').default
    case 'Grid': return require('./svg/grid.svg').default
    case 'Guitar': return require('./svg/guitar.svg').default
    case 'Hammer': return require('./svg/hammer.svg').default
    case 'HandCoin': return require('./svg/hand-coin.svg').default
    case 'Hand': return require('./svg/hand.svg').default
    case 'Hanger': return require('./svg/hanger.svg').default
    case 'HardDrive': return require('./svg/hard-drive.svg').default
    case 'Hat': return require('./svg/hat.svg').default
    case 'Headphones': return require('./svg/headphones.svg').default
    case 'HeartFilled': return require('./svg/heart-filled.svg').default
    case 'HeartPulse': return require('./svg/heart-pulse.svg').default
    case 'Heart': return require('./svg/heart.svg').default
    case 'Help': return require('./svg/help.svg').default
    case 'Hex': return require('./svg/hex.svg').default
    case 'Hexagram': return require('./svg/hexagram.svg').default
    case 'History': return require('./svg/history.svg').default
    case 'Home': return require('./svg/home.svg').default
    case 'Hospital': return require('./svg/hospital.svg').default
    case 'Hourglass': return require('./svg/hourglass.svg').default
    case 'IceCream': return require('./svg/ice-cream.svg').default
    case 'Image': return require('./svg/image.svg').default
    case 'Inbox': return require('./svg/inbox.svg').default
    case 'Info': return require('./svg/info.svg').default
    case 'KeyRound': return require('./svg/key-round.svg').default
    case 'Key': return require('./svg/key.svg').default
    case 'Keyboard': return require('./svg/keyboard.svg').default
    case 'Lamp': return require('./svg/lamp.svg').default
    case 'Laptop': return require('./svg/laptop.svg').default
    case 'Layers': return require('./svg/layers.svg').default
    case 'Leaf': return require('./svg/leaf.svg').default
    case 'Lightbulb': return require('./svg/lightbulb.svg').default
    case 'Link': return require('./svg/link.svg').default
    case 'Lipstick': return require('./svg/lipstick.svg').default
    case 'List': return require('./svg/list.svg').default
    case 'Lock': return require('./svg/lock.svg').default
    case 'Lotus': return require('./svg/lotus.svg').default
    case 'Luggage': return require('./svg/luggage.svg').default
    case 'Magnet': return require('./svg/magnet.svg').default
    case 'MailOpen': return require('./svg/mail-open.svg').default
    case 'Mail': return require('./svg/mail.svg').default
    case 'Map': return require('./svg/map.svg').default
    case 'Mark': return require('./svg/mark.svg').default
    case 'Mars': return require('./svg/mars.svg').default
    case 'Mask': return require('./svg/mask.svg').default
    case 'Maximize': return require('./svg/maximize.svg').default
    case 'Megaphone': return require('./svg/megaphone.svg').default
    case 'Menu': return require('./svg/menu.svg').default
    case 'Mercury': return require('./svg/mercury.svg').default
    case 'MicOff': return require('./svg/mic-off.svg').default
    case 'Mic': return require('./svg/mic.svg').default
    case 'Milk': return require('./svg/milk.svg').default
    case 'MinusCircle': return require('./svg/minus-circle.svg').default
    case 'Minus': return require('./svg/minus.svg').default
    case 'MoneyBill': return require('./svg/money-bill.svg').default
    case 'Monitor': return require('./svg/monitor.svg').default
    case 'Moon': return require('./svg/moon.svg').default
    case 'MoreVertical': return require('./svg/more-vertical.svg').default
    case 'More': return require('./svg/more.svg').default
    case 'MortarPestle': return require('./svg/mortar-pestle.svg').default
    case 'Mountain': return require('./svg/mountain.svg').default
    case 'Mushroom': return require('./svg/mushroom.svg').default
    case 'MusicNote': return require('./svg/music-note.svg').default
    case 'Navigation': return require('./svg/navigation.svg').default
    case 'Needle': return require('./svg/needle.svg').default
    case 'Noodles': return require('./svg/noodles.svg').default
    case 'Note': return require('./svg/note.svg').default
    case 'NutBolt': return require('./svg/nut-bolt.svg').default
    case 'Palette': return require('./svg/palette.svg').default
    case 'PalmTree': return require('./svg/palm-tree.svg').default
    case 'Paperclip': return require('./svg/paperclip.svg').default
    case 'Parking': return require('./svg/parking.svg').default
    case 'Passport': return require('./svg/passport.svg').default
    case 'Pause': return require('./svg/pause.svg').default
    case 'Paw': return require('./svg/paw.svg').default
    case 'Pencil': return require('./svg/pencil.svg').default
    case 'People': return require('./svg/people.svg').default
    case 'Percent': return require('./svg/percent.svg').default
    case 'Perfume': return require('./svg/perfume.svg').default
    case 'PersonAdd': return require('./svg/person-add.svg').default
    case 'Person': return require('./svg/person.svg').default
    case 'Phone': return require('./svg/phone.svg').default
    case 'Piano': return require('./svg/piano.svg').default
    case 'Pickaxe': return require('./svg/pickaxe.svg').default
    case 'PiggyBank': return require('./svg/piggy-bank.svg').default
    case 'Pill': return require('./svg/pill.svg').default
    case 'Pin': return require('./svg/pin.svg').default
    case 'Pizza': return require('./svg/pizza.svg').default
    case 'Plane': return require('./svg/plane.svg').default
    case 'Planet': return require('./svg/planet.svg').default
    case 'PlayCircle': return require('./svg/play-circle.svg').default
    case 'Play': return require('./svg/play.svg').default
    case 'Plug': return require('./svg/plug.svg').default
    case 'PlusCircle': return require('./svg/plus-circle.svg').default
    case 'Plus': return require('./svg/plus.svg').default
    case 'Popcorn': return require('./svg/popcorn.svg').default
    case 'Potion': return require('./svg/potion.svg').default
    case 'Pound': return require('./svg/pound.svg').default
    case 'Printer': return require('./svg/printer.svg').default
    case 'Puzzle': return require('./svg/puzzle.svg').default
    case 'Qr': return require('./svg/qr.svg').default
    case 'Quintessence': return require('./svg/quintessence.svg').default
    case 'Rainbow': return require('./svg/rainbow.svg').default
    case 'Receipt': return require('./svg/receipt.svg').default
    case 'Redo': return require('./svg/redo.svg').default
    case 'Refresh': return require('./svg/refresh.svg').default
    case 'Restaurant': return require('./svg/restaurant.svg').default
    case 'Ring': return require('./svg/ring.svg').default
    case 'Road': return require('./svg/road.svg').default
    case 'Rocket': return require('./svg/rocket.svg').default
    case 'Router': return require('./svg/router.svg').default
    case 'Rss': return require('./svg/rss.svg').default
    case 'Ruler': return require('./svg/ruler.svg').default
    case 'Running': return require('./svg/running.svg').default
    case 'Salad': return require('./svg/salad.svg').default
    case 'Salt': return require('./svg/salt.svg').default
    case 'Save': return require('./svg/save.svg').default
    case 'Saw': return require('./svg/saw.svg').default
    case 'Scale': return require('./svg/scale.svg').default
    case 'Scales': return require('./svg/scales.svg').default
    case 'School': return require('./svg/school.svg').default
    case 'Scissors': return require('./svg/scissors.svg').default
    case 'Scooter': return require('./svg/scooter.svg').default
    case 'Screwdriver': return require('./svg/screwdriver.svg').default
    case 'Scroll': return require('./svg/scroll.svg').default
    case 'Search': return require('./svg/search.svg').default
    case 'Send': return require('./svg/send.svg').default
    case 'Server': return require('./svg/server.svg').default
    case 'Settings': return require('./svg/settings.svg').default
    case 'Share': return require('./svg/share.svg').default
    case 'ShieldCheck': return require('./svg/shield-check.svg').default
    case 'ShieldKey': return require('./svg/shield-key.svg').default
    case 'Shield': return require('./svg/shield.svg').default
    case 'Ship': return require('./svg/ship.svg').default
    case 'Shirt': return require('./svg/shirt.svg').default
    case 'Shoe': return require('./svg/shoe.svg').default
    case 'Shovel': return require('./svg/shovel.svg').default
    case 'Sidebar': return require('./svg/sidebar.svg').default
    case 'SigilBlade': return require('./svg/sigil-blade.svg').default
    case 'SigilCardinal': return require('./svg/sigil-cardinal.svg').default
    case 'SigilEye': return require('./svg/sigil-eye.svg').default
    case 'SigilFeather': return require('./svg/sigil-feather.svg').default
    case 'SigilFlame': return require('./svg/sigil-flame.svg').default
    case 'SigilFlask': return require('./svg/sigil-flask.svg').default
    case 'SigilHeptagram': return require('./svg/sigil-heptagram.svg').default
    case 'SigilHexnested': return require('./svg/sigil-hexnested.svg').default
    case 'SigilKey': return require('./svg/sigil-key.svg').default
    case 'SigilLeaf': return require('./svg/sigil-leaf.svg').default
    case 'SigilMoon': return require('./svg/sigil-moon.svg').default
    case 'SigilOctagram': return require('./svg/sigil-octagram.svg').default
    case 'SigilPentagram': return require('./svg/sigil-pentagram.svg').default
    case 'SigilSolomon': return require('./svg/sigil-solomon.svg').default
    case 'SigilSpiralsquare': return require('./svg/sigil-spiralsquare.svg').default
    case 'SigilTriquetra': return require('./svg/sigil-triquetra.svg').default
    case 'SigilVesica': return require('./svg/sigil-vesica.svg').default
    case 'SigilWheel': return require('./svg/sigil-wheel.svg').default
    case 'Sigil': return require('./svg/sigil.svg').default
    case 'SkipBack': return require('./svg/skip-back.svg').default
    case 'SkipForward': return require('./svg/skip-forward.svg').default
    case 'Skull': return require('./svg/skull.svg').default
    case 'Sliders': return require('./svg/sliders.svg').default
    case 'Smartphone': return require('./svg/smartphone.svg').default
    case 'Snowflake': return require('./svg/snowflake.svg').default
    case 'Snowman': return require('./svg/snowman.svg').default
    case 'Soda': return require('./svg/soda.svg').default
    case 'Sort': return require('./svg/sort.svg').default
    case 'Spinner': return require('./svg/spinner.svg').default
    case 'Sprig': return require('./svg/sprig.svg').default
    case 'Sprout': return require('./svg/sprout.svg').default
    case 'Square': return require('./svg/square.svg').default
    case 'StarFilled': return require('./svg/star-filled.svg').default
    case 'Star': return require('./svg/star.svg').default
    case 'Stethoscope': return require('./svg/stethoscope.svg').default
    case 'Stop': return require('./svg/stop.svg').default
    case 'Store': return require('./svg/store.svg').default
    case 'Stroller': return require('./svg/stroller.svg').default
    case 'Sulfur': return require('./svg/sulfur.svg').default
    case 'Sun': return require('./svg/sun.svg').default
    case 'Sunglasses': return require('./svg/sunglasses.svg').default
    case 'Sunrise': return require('./svg/sunrise.svg').default
    case 'Sushi': return require('./svg/sushi.svg').default
    case 'Syringe': return require('./svg/syringe.svg').default
    case 'Taco': return require('./svg/taco.svg').default
    case 'Tag': return require('./svg/tag.svg').default
    case 'Target': return require('./svg/target.svg').default
    case 'Taxi': return require('./svg/taxi.svg').default
    case 'Teddy': return require('./svg/teddy.svg').default
    case 'Tent': return require('./svg/tent.svg').default
    case 'TheaterMasks': return require('./svg/theater-masks.svg').default
    case 'Thermometer': return require('./svg/thermometer.svg').default
    case 'Thermostat': return require('./svg/thermostat.svg').default
    case 'ThumbsDown': return require('./svg/thumbs-down.svg').default
    case 'ThumbsUp': return require('./svg/thumbs-up.svg').default
    case 'Thumbtack': return require('./svg/thumbtack.svg').default
    case 'Tick': return require('./svg/tick.svg').default
    case 'Ticket': return require('./svg/ticket.svg').default
    case 'Timer': return require('./svg/timer.svg').default
    case 'ToggleOff': return require('./svg/toggle-off.svg').default
    case 'ToggleOn': return require('./svg/toggle-on.svg').default
    case 'Toolbox': return require('./svg/toolbox.svg').default
    case 'Tooth': return require('./svg/tooth.svg').default
    case 'TrafficLight': return require('./svg/traffic-light.svg').default
    case 'Train': return require('./svg/train.svg').default
    case 'Trash': return require('./svg/trash.svg').default
    case 'Tree': return require('./svg/tree.svg').default
    case 'TrendingDown': return require('./svg/trending-down.svg').default
    case 'TrendingUp': return require('./svg/trending-up.svg').default
    case 'TriangleDown': return require('./svg/triangle-down.svg').default
    case 'Triangle': return require('./svg/triangle.svg').default
    case 'Trophy': return require('./svg/trophy.svg').default
    case 'Truck': return require('./svg/truck.svg').default
    case 'Tv': return require('./svg/tv.svg').default
    case 'Umbrella': return require('./svg/umbrella.svg').default
    case 'Undo': return require('./svg/undo.svg').default
    case 'Unlink': return require('./svg/unlink.svg').default
    case 'Unlock': return require('./svg/unlock.svg').default
    case 'Upload': return require('./svg/upload.svg').default
    case 'UserCircle': return require('./svg/user-circle.svg').default
    case 'Utensils': return require('./svg/utensils.svg').default
    case 'Vault': return require('./svg/vault.svg').default
    case 'Venus': return require('./svg/venus.svg').default
    case 'Video': return require('./svg/video.svg').default
    case 'VolumeOff': return require('./svg/volume-off.svg').default
    case 'Volume': return require('./svg/volume.svg').default
    case 'Wallet': return require('./svg/wallet.svg').default
    case 'Warning': return require('./svg/warning.svg').default
    case 'Washer': return require('./svg/washer.svg').default
    case 'Watch': return require('./svg/watch.svg').default
    case 'Waves': return require('./svg/waves.svg').default
    case 'WeightScale': return require('./svg/weight-scale.svg').default
    case 'Wheelchair': return require('./svg/wheelchair.svg').default
    case 'Wifi': return require('./svg/wifi.svg').default
    case 'Wind': return require('./svg/wind.svg').default
    case 'Wine': return require('./svg/wine.svg').default
    case 'Wordmark': return require('./svg/wordmark.svg').default
    case 'Wrench': return require('./svg/wrench.svg').default
    case 'XCircle': return require('./svg/x-circle.svg').default
    case 'Yen': return require('./svg/yen.svg').default
    default: return null
  }
}
