import { createThemeContract } from '@vanilla-extract/css'

export const vars = createThemeContract({
  color: {
    bg: null,
    bg2: null,
    bgSunken: null,
    surface: null,
    surface2: null,
    fg: null,
    fg2: null,
    fg3: null,
    fgMute: null,
    border: null,
    border2: null,
    borderMute: null,
    rule: null,
    accent: null,
    accentFg: null,
    accent2: null,
    accent3: null,
    success: null,
    warn: null,
    danger: null,
    info: null,
    selectionBg: null,
    selectionFg: null,
    // Material system — only populated inside .material objects; never used on the working page
    material: null,
    materialFg: null,
    materialBtnFg: null,
    metal: null,
    metalDeep: null,
  },
  font: {
    display: null,
    body: null,
    mono: null,
  },
  space: {
    sp1: null,
    sp2: null,
    sp3: null,
    sp4: null,
    sp5: null,
    sp6: null,
    sp7: null,
    sp8: null,
    sp9: null,
    sp10: null,
    sp11: null,
    sp12: null,
  },
  radius: {
    none: null,
    hairline: null,
    sm: null,
    pill: null,
  },
  shadow: {
    stamp: null,
    stampLg: null,
    press: null,
    soft: null,
  },
  duration: {
    fast: null,
    base: null,
    slow: null,
  },
  ease: {
    out: null,
    snap: null,
  },
})
