export type ComponentSize = 'sm' | 'md' | 'lg'

export type ButtonVariant = 'primary' | 'secondary' | 'accent' | 'ghost' | 'danger'

export type BadgeTone = 'saved' | 'drafting' | 'stopped' | 'archived' | 'neutral'
export type BadgeVariant = 'outline' | 'solid'

export type GlyphName =
  | 'arrow-right'
  | 'arrow-up'
  | 'asterism'
  | 'book'
  | 'circle'
  | 'compass'
  | 'cross'
  | 'eye'
  | 'feather'
  | 'fern'
  | 'flask'
  | 'flourish'
  | 'hand'
  | 'hex'
  | 'key'
  | 'leaf'
  | 'mark'
  | 'mercury'
  | 'minus'
  | 'moon'
  | 'plus'
  | 'salt'
  | 'scroll'
  | 'sigil'
  | 'sprig'
  | 'square'
  | 'star'
  | 'sulfur'
  | 'sun'
  | 'tick'
  | 'triangle'
  | 'triangle-down'
  | 'wordmark'

export type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

export type SortDirection = 'asc' | 'desc' | null
