/** Standard three-stop size scale shared across components. */
export type ComponentSize = 'sm' | 'md' | 'lg'

/**
 * Visual variant for the {@link Button} component.
 * - `primary` — high-emphasis, ink fill with stamp shadow
 * - `secondary` — medium-emphasis, surface fill
 * - `accent` — accent-colour fill; one per view
 * - `ghost` — minimal border-only; for toolbar/icon buttons
 * - `danger` — destructive actions
 */
export type ButtonVariant = 'primary' | 'secondary' | 'accent' | 'ghost' | 'danger'

/**
 * Semantic colour tone for the {@link Badge} component.
 * - `saved` — green; completed or published
 * - `drafting` — amber; in-progress or pending
 * - `stopped` — red; error, blocked, or inactive
 * - `archived` — muted; historical or soft-deleted
 * - `neutral` — no semantic weight; informational
 */
export type BadgeTone = 'saved' | 'drafting' | 'stopped' | 'archived' | 'neutral'

/**
 * Visual style for the {@link Badge} component.
 * - `outline` — tinted background with border (lighter weight)
 * - `solid` — filled background (higher visual weight)
 */
export type BadgeVariant = 'outline' | 'solid'

/**
 * Union of all valid glyph names in the Achery icon set (394 glyphs + 3 brand marks).
 * Pass to the `name` prop of {@link Glyph}, or to any component that accepts
 * a `glyph?: GlyphName` prop (Button, Card, Sidebar items, etc.).
 */
export type GlyphName =
  | 'acorn'
  | 'alarm'
  | 'anchor'
  | 'ankh'
  | 'anvil'
  | 'apple'
  | 'archive'
  | 'arrow-down'
  | 'arrow-down-right'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'arrow-up-right'
  | 'asterism'
  | 'at-sign'
  | 'atm'
  | 'award'
  | 'axe'
  | 'baby-bottle'
  | 'backpack'
  | 'bag'
  | 'balloon'
  | 'ban'
  | 'bandage'
  | 'bank'
  | 'barcode'
  | 'basket'
  | 'battery'
  | 'bed'
  | 'beer'
  | 'bell'
  | 'bell-off'
  | 'bike'
  | 'bird'
  | 'bitcoin'
  | 'blocks'
  | 'bolt'
  | 'bone'
  | 'book'
  | 'bookmark'
  | 'bottle'
  | 'box'
  | 'brain'
  | 'bread'
  | 'briefcase'
  | 'broom'
  | 'brush'
  | 'bug'
  | 'building'
  | 'burger'
  | 'bus'
  | 'cactus'
  | 'cake'
  | 'calculator'
  | 'calendar'
  | 'calendar-check'
  | 'camera'
  | 'campfire'
  | 'candle'
  | 'candy'
  | 'car'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'caret-up'
  | 'cart'
  | 'cat'
  | 'chart-bar'
  | 'chart-line'
  | 'chart-pie'
  | 'chat'
  | 'chat-dots'
  | 'check-circle'
  | 'chess'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevrons-left'
  | 'chevrons-right'
  | 'circle'
  | 'clapperboard'
  | 'clipboard'
  | 'clock'
  | 'close'
  | 'cloud'
  | 'cloud-rain'
  | 'cloud-sun'
  | 'cocktail'
  | 'coffee'
  | 'coin'
  | 'coins'
  | 'collapse'
  | 'columns'
  | 'comet'
  | 'comments'
  | 'compass'
  | 'cookie'
  | 'copy'
  | 'couch'
  | 'cpu'
  | 'credit-card'
  | 'croissant'
  | 'cross'
  | 'crosshair'
  | 'crown'
  | 'crystal'
  | 'cup'
  | 'database'
  | 'dice'
  | 'dog'
  | 'dollar'
  | 'donut'
  | 'door'
  | 'download'
  | 'drafting-compass'
  | 'drag'
  | 'dress'
  | 'droplet'
  | 'dumbbell'
  | 'edit'
  | 'egg'
  | 'element-air'
  | 'element-earth'
  | 'element-fire'
  | 'element-water'
  | 'eraser'
  | 'euro'
  | 'exchange'
  | 'expand'
  | 'external-link'
  | 'eye'
  | 'eye-off'
  | 'factory'
  | 'feather'
  | 'fern'
  | 'file'
  | 'file-plus'
  | 'film'
  | 'filter'
  | 'fingerprint'
  | 'fire'
  | 'fire-extinguisher'
  | 'first-aid'
  | 'fish'
  | 'fish-hook'
  | 'flag'
  | 'flask'
  | 'flourish'
  | 'flower'
  | 'folder'
  | 'folder-open'
  | 'fuel'
  | 'gamepad'
  | 'gavel'
  | 'gear'
  | 'gem'
  | 'gift'
  | 'glasses'
  | 'globe'
  | 'grid'
  | 'guitar'
  | 'hammer'
  | 'hand'
  | 'hand-coin'
  | 'hanger'
  | 'hard-drive'
  | 'hat'
  | 'headphones'
  | 'heart'
  | 'heart-filled'
  | 'heart-pulse'
  | 'help'
  | 'hex'
  | 'hexagram'
  | 'history'
  | 'home'
  | 'hospital'
  | 'hourglass'
  | 'ice-cream'
  | 'image'
  | 'inbox'
  | 'info'
  | 'key'
  | 'key-round'
  | 'keyboard'
  | 'lamp'
  | 'laptop'
  | 'layers'
  | 'leaf'
  | 'lightbulb'
  | 'link'
  | 'lipstick'
  | 'list'
  | 'lock'
  | 'lotus'
  | 'luggage'
  | 'magnet'
  | 'mail'
  | 'mail-open'
  | 'map'
  | 'mark'
  | 'mars'
  | 'mask'
  | 'maximize'
  | 'megaphone'
  | 'menu'
  | 'mercury'
  | 'mic'
  | 'mic-off'
  | 'milk'
  | 'minus'
  | 'minus-circle'
  | 'money-bill'
  | 'monitor'
  | 'moon'
  | 'more'
  | 'more-vertical'
  | 'mortar-pestle'
  | 'mountain'
  | 'mushroom'
  | 'music-note'
  | 'navigation'
  | 'needle'
  | 'noodles'
  | 'note'
  | 'nut-bolt'
  | 'palette'
  | 'palm-tree'
  | 'paperclip'
  | 'parking'
  | 'passport'
  | 'pause'
  | 'paw'
  | 'pencil'
  | 'people'
  | 'percent'
  | 'perfume'
  | 'person'
  | 'person-add'
  | 'phone'
  | 'piano'
  | 'pickaxe'
  | 'piggy-bank'
  | 'pill'
  | 'pin'
  | 'pizza'
  | 'plane'
  | 'planet'
  | 'play'
  | 'play-circle'
  | 'plug'
  | 'plus'
  | 'plus-circle'
  | 'popcorn'
  | 'potion'
  | 'pound'
  | 'printer'
  | 'puzzle'
  | 'qr'
  | 'quintessence'
  | 'rainbow'
  | 'receipt'
  | 'redo'
  | 'refresh'
  | 'restaurant'
  | 'ring'
  | 'road'
  | 'rocket'
  | 'router'
  | 'rss'
  | 'ruler'
  | 'running'
  | 'salad'
  | 'salt'
  | 'save'
  | 'saw'
  | 'scale'
  | 'scales'
  | 'school'
  | 'scissors'
  | 'scooter'
  | 'screwdriver'
  | 'scroll'
  | 'search'
  | 'send'
  | 'server'
  | 'settings'
  | 'share'
  | 'shield'
  | 'shield-check'
  | 'shield-key'
  | 'ship'
  | 'shirt'
  | 'shoe'
  | 'shovel'
  | 'sidebar'
  | 'sigil'
  | 'sigil-blade'
  | 'sigil-cardinal'
  | 'sigil-eye'
  | 'sigil-feather'
  | 'sigil-flame'
  | 'sigil-flask'
  | 'sigil-heptagram'
  | 'sigil-hexnested'
  | 'sigil-key'
  | 'sigil-leaf'
  | 'sigil-moon'
  | 'sigil-octagram'
  | 'sigil-pentagram'
  | 'sigil-solomon'
  | 'sigil-spiralsquare'
  | 'sigil-triquetra'
  | 'sigil-vesica'
  | 'sigil-wheel'
  | 'skip-back'
  | 'skip-forward'
  | 'skull'
  | 'sliders'
  | 'smartphone'
  | 'snowflake'
  | 'snowman'
  | 'soda'
  | 'sort'
  | 'spinner'
  | 'sprig'
  | 'sprout'
  | 'square'
  | 'star'
  | 'star-filled'
  | 'stethoscope'
  | 'stop'
  | 'store'
  | 'stroller'
  | 'sulfur'
  | 'sun'
  | 'sunglasses'
  | 'sunrise'
  | 'sushi'
  | 'syringe'
  | 'taco'
  | 'tag'
  | 'target'
  | 'taxi'
  | 'teddy'
  | 'tent'
  | 'theater-masks'
  | 'thermometer'
  | 'thermostat'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'thumbtack'
  | 'tick'
  | 'ticket'
  | 'timer'
  | 'toggle-off'
  | 'toggle-on'
  | 'toolbox'
  | 'tooth'
  | 'traffic-light'
  | 'train'
  | 'trash'
  | 'tree'
  | 'trending-down'
  | 'trending-up'
  | 'triangle'
  | 'triangle-down'
  | 'trophy'
  | 'truck'
  | 'tv'
  | 'umbrella'
  | 'undo'
  | 'unlink'
  | 'unlock'
  | 'upload'
  | 'user-circle'
  | 'utensils'
  | 'vault'
  | 'venus'
  | 'video'
  | 'volume'
  | 'volume-off'
  | 'wallet'
  | 'warning'
  | 'washer'
  | 'watch'
  | 'waves'
  | 'weight-scale'
  | 'wheelchair'
  | 'wifi'
  | 'wind'
  | 'wine'
  | 'wordmark'
  | 'wrench'
  | 'x-circle'
  | 'yen'

/** @internal */
export type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

/**
 * Sort direction for the {@link Table} component.
 * `null` means no active sort (natural/insertion order).
 */
export type SortDirection = 'asc' | 'desc' | null
